kind: Service
apiVersion: v1
metadata:
  name: launcher
  labels:
    heritage: skyboat.io
  annotations:
    skyboat.io/svc: internal
spec:
  selector:
    component.skyboat.io: launcher
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 2390